## Creación de array

In [34]:
import numpy as np


- array()
- zeros()
- ones()
- eye()
- linspaces()
- random.rand()
- random.randint()

In [45]:
np.array([1, 2, 3])  # Array de una dimensión

array([1, 2, 3])

In [46]:
np.array([(1, 2, 3), (7, 8, 9)])  # Array de dos dimensiones

array([[1, 2, 3],
       [7, 8, 9]])

In [47]:
np.zeros(10)  # Array de una dimensión con 10 elementos iguales a 0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
np.ones(10)  # Array de una dimensión con 10 elementos iguales a 1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [49]:
np.eye(5)  # Array de dos dimensiones de 5x5 elementos iguales a 0, pero 1 en su diagonal

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
np.linspace(0, 10, 5)  # Array de una dimensión con 5 elementos uniformemente distribuidos entre 0 y 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [52]:
np.random.rand(50)  # Array de una dimensión con 50 elementos entre 0 (incluido) y 1 (no incluido)

array([0.61209922, 0.72690251, 0.60157257, 0.97941852, 0.91832729,
       0.53355238, 0.52179378, 0.31698635, 0.31950497, 0.93415692,
       0.51322474, 0.24076861, 0.02947823, 0.96667814, 0.54481288,
       0.19854269, 0.33790087, 0.82092774, 0.60175532, 0.93685612,
       0.02514253, 0.81616535, 0.82905521, 0.10997082, 0.51773871,
       0.42151164, 0.35380053, 0.67638577, 0.38920823, 0.37891138,
       0.82250943, 0.46085863, 0.13444911, 0.61272114, 0.3537625 ,
       0.39235011, 0.23750426, 0.74187744, 0.22852038, 0.53156689,
       0.04100285, 0.34456299, 0.12538526, 0.54595544, 0.6827185 ,
       0.89324682, 0.48534172, 0.48120886, 0.78448734, 0.80656175])

In [53]:
np.random.rand(3, 4)  # Array de dos dimensiones 3x4 con elementos entre 0 (incluido) y 1 (no incluido)

array([[0.11631268, 0.56758139, 0.82333293, 0.73655164],
       [0.87420398, 0.49957312, 0.43997557, 0.20380229],
       [0.43351331, 0.33889909, 0.51051769, 0.1020349 ]])

In [54]:
np.random.rand(4, 5)*100  # Array de 4x5 con valores entre 0 y 100

array([[25.34395938, 26.71665693, 24.8506284 , 43.09724305, 42.73889928],
       [89.99592715, 71.04354616, 64.31597438, 52.71890849, 22.28682252],
       [ 0.59130822, 62.2683721 ,  3.42550108, 30.02583591, 14.03826104],
       [ 2.12058742, 80.4171192 , 72.19997077, 67.23307601, 59.12724723]])

In [55]:
np.random.randint(10, size=(2,3))  # Array de dos dimensiones 2x3 con elementos enteros entre 0 y 10

array([[9, 3, 0],
       [5, 1, 8]])