# Introducción a Numpy

> NumPy es una biblioteca de Python que da soporte para crear vectores y matrices grandes multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel para operar con ellas.

Sitio oficial: [numpy.org](https://numpy.org)

Documentación oficial: [numpy.org/doc/stable/](https://numpy.org/doc/stable/)

In [1]:
import numpy as np

## Creación de array

- array()
- zeros()
- ones()
- linspaces()
- random.rand()

In [3]:
np.array([1, 2, 3])  # Array de una dimensión

array([1, 2, 3])

In [2]:
np.array([(1, 2, 3), (7, 8, 9)])  # Array de dos dimensiones

array([[1, 2, 3],
       [7, 8, 9]])

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
np.random.rand(50)

array([0.80622545, 0.02996572, 0.51643056, 0.1075533 , 0.76908978,
       0.42179431, 0.25700384, 0.4502794 , 0.31652859, 0.39630882,
       0.4266884 , 0.54690869, 0.07504135, 0.09567996, 0.81163828,
       0.46959775, 0.64811764, 0.29687717, 0.72932392, 0.76762342,
       0.89065062, 0.78467267, 0.53693297, 0.03045665, 0.65642421,
       0.30733132, 0.37883967, 0.91096903, 0.17568474, 0.85860677,
       0.74774892, 0.21845653, 0.71769842, 0.23663513, 0.88662321,
       0.84959148, 0.09146553, 0.09905696, 0.0727032 , 0.06096832,
       0.74950331, 0.38957089, 0.70141756, 0.88346993, 0.40070635,
       0.40489457, 0.86860555, 0.5688051 , 0.71096624, 0.48266758])

In [12]:
np.random.rand(3, 4)

array([[0.92190802, 0.74598688, 0.75884849, 0.29692832],
       [0.03068701, 0.46815299, 0.42088944, 0.70359792],
       [0.43365566, 0.18094837, 0.12889737, 0.57306838]])

In [5]:
np.random.rand(4, 5)*100  # Array de 4x5 con valores entre 0 y 100

array([[91.81674294, 37.87953081, 74.37547376, 54.29901529, 28.39509754],
       [86.53421609, 95.89739471, 93.42963114, 97.32029912, 97.69381345],
       [18.91135138, 16.69843281, 11.25301132, 13.81691617, 52.54658884],
       [37.21285163, 33.94239525, 30.28308091, 24.02954286, 37.38053286]])

In [14]:
my_array = np.random.rand(10)
my_array.min()

0.03908292163209459